#!/usr/bin/env python3

import sys
from main import main

def check_argv_error(argv):
    if len(argv) != 4:
        print("Error:",len(argv) - 1,"arguments given but 3 are required.",
            file = sys.stderr)
        return True
    for i in range(1, len(argv)):
        try:
            int(argv[i])
        except ValueError:
            print("Error: arguments must be integer.", file = sys.stderr)
            return True
    if int(argv[3]) < 0 or int(argv[3]) > 2:
        print("Error: third argument must be 0, 1 or 2.", file = sys.stderr)
        return True
    return False

if __name__ == "__main__":
    if check_argv_error(sys.argv):
        sys.exit(84)
    main(sys.argv)
